"""Add timing fields to Submission

Revision ID: 48779265f21a
Revises: 837430d81687
Create Date: 2026-04-20 21:13:24.861940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48779265f21a'
down_revision = '837430d81687'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('build_time', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_run_time', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_column('total_run_time')
        batch_op.drop_column('build_time')

    # ### end Alembic commands ###
