"""Add Exam entities

Revision ID: 627cd10e3544
Revises: bad8aa936079
Create Date: 2026-04-07 20:35:27.105753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '627cd10e3544'
down_revision = 'bad8aa936079'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exam_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_submission_exam_id'), ['exam_id'], unique=False)
        batch_op.create_foreign_key('fk_submission_exam_id', 'exam', ['exam_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_submission_exam_id'))
        batch_op.drop_column('exam_id')

    # ### end Alembic commands ###
