"""add requirements to exam

Revision ID: 837430d81687
Revises: 083c878e6520
Create Date: 2026-04-20 13:00:12.315911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '837430d81687'
down_revision = '083c878e6520'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requirements', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.drop_column('requirements')

    # ### end Alembic commands ###
