"""Change the exam id to nullable on submission

Revision ID: c601774e1258
Revises: 627cd10e3544
Create Date: 2026-04-07 20:37:35.054159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c601774e1258'
down_revision = '627cd10e3544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.alter_column('exam_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.alter_column('exam_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
