"""add role and group to user

Revision ID: dcc40d0aceaa
Revises: 0f387e2ac97d
Create Date: 2026-03-15 13:40:18.840253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcc40d0aceaa'
down_revision = '0f387e2ac97d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('group', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_group'), ['group'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_role'), ['role'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_role'))
        batch_op.drop_index(batch_op.f('ix_user_group'))
        batch_op.drop_column('group')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
